export const citiesData = [
    'Karachi',
    'Lahore',
    'Faisalabad',
    'Rawalpindi',
    'Islamabad',
    'Multan',
    'Hyderabad',
    'Quetta',
    'Peshawar',
    'Gujranwala',
    'Sialkot',
    'Bahawalpur',
    'Sargodha',
    'Sukkur',
    'Larkana',
    'Sheikhupura',
    'Mirpur Khas',
    'Rahim Yar Khan',
    'Gujrat',
    'Jhang',
    'Mardan',
    'Kasur',
    'Dera Ghazi Khan',
    'Sahiwal',
    'Nawabshah',
    'Mingora',
    'Okara',
    'Mirpur',
    'Chiniot',
    'Kamoke',
    'Mandi Bahauddin',
    'Jacobabad',
    'Jhelum',
    'Khanewal',
    'Khairpur',
    'Khuzdar',
    'Pakpattan',
    'Hub',
    'Hafizabad',
    'Kohat',
    'Lodhran',
    'Malakand',
    'Mianwali',
    'Muzaffargarh',
    'Khanpur',
    'Gojra',
    'Mandi',
    'Daska',
    'Tando Allahyar',
  ];